In [13]:
import pandas as pd

df1 = pd.read_csv("https://raw.githubusercontent.com/NelsonJavierAguilera/Proyectos_Personales/main/AnyConv.com__ventasTotalesv2.csv")

df1

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
0,1/1/2016,Steve Ashton,Norte,Medias Femeninas,Vestimenta,6,18.00
1,1/1/2016,Trevor Snodgrass,Oeste,Chocolate,Comestibles,8,3.84
2,1/1/2016,Sarah Bond,Sur,Gorras,Vestimenta,3,6.30
3,1/1/2016,Desmond Delaney,Sur,Sánguche de Queso,Comestibles,9,14.40
4,1/1/2016,Desmond Delaney,Este,Chocolate,Comestibles,14,6.72
...,...,...,...,...,...,...,...
455,1/31/2016,Sarah Bond,Sur,Bufanda,Vestimenta,6,16.50
456,1/31/2016,Dustin Gee,Este,Sandalias,Vestimenta,11,115.50
457,1/31/2016,Dustin Gee,Este,Sánguche de Queso,Comestibles,4,6.40
458,1/31/2016,Dustin Gee,Norte,Escobillón,Hogar,8,6.80
459,1/31/2016,Trevor Snodgrass,Sur,Pepinillo,Comestibles,7,2.10

In [26]:
df1.Vendedor.value_counts(ascending=True, dropna=False)

Boris Stanford      69
Dustin Gee          70
Trevor Snodgrass    75
Desmond Delaney     76
Steve Ashton        84
Sarah Bond          86
Name: Vendedor, dtype: int64